name: epi2melabs-wf-mpx
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat >=0.6.9
    - pysam >=0.17.0
    - fastcat
    - epi2melabs
    - minimap2 ==2.23
    - pomoxis
    - medaka==1.5.0
    - mosdepth
    - aplanat
    - pandas
    - pyvcf
    - flye
    - bedtools
    - vcf-annotator
